/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as MainImport } from './routes/main'
import { Route as IndexImport } from './routes/index'

// Create Virtual Routes

const HomeLazyImport = createFileRoute('/home')()
const TasksIndexLazyImport = createFileRoute('/tasks/')()
const LoginIndexLazyImport = createFileRoute('/login/')()
const FoldersIndexLazyImport = createFileRoute('/folders/')()
const TasksTaskIdLazyImport = createFileRoute('/tasks/$taskId')()
const FoldersFolderIdLazyImport = createFileRoute('/folders/$folderId')()

// Create/Update Routes

const HomeLazyRoute = HomeLazyImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/home.lazy').then((d) => d.Route))

const MainRoute = MainImport.update({
  id: '/main',
  path: '/main',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const TasksIndexLazyRoute = TasksIndexLazyImport.update({
  id: '/tasks/',
  path: '/tasks/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/tasks/index.lazy').then((d) => d.Route))

const LoginIndexLazyRoute = LoginIndexLazyImport.update({
  id: '/login/',
  path: '/login/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/login/index.lazy').then((d) => d.Route))

const FoldersIndexLazyRoute = FoldersIndexLazyImport.update({
  id: '/folders/',
  path: '/folders/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/folders/index.lazy').then((d) => d.Route))

const TasksTaskIdLazyRoute = TasksTaskIdLazyImport.update({
  id: '/tasks/$taskId',
  path: '/tasks/$taskId',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/tasks/$taskId.lazy').then((d) => d.Route))

const FoldersFolderIdLazyRoute = FoldersFolderIdLazyImport.update({
  id: '/folders/$folderId',
  path: '/folders/$folderId',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./routes/folders/$folderId.lazy').then((d) => d.Route),
)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/main': {
      id: '/main'
      path: '/main'
      fullPath: '/main'
      preLoaderRoute: typeof MainImport
      parentRoute: typeof rootRoute
    }
    '/home': {
      id: '/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeLazyImport
      parentRoute: typeof rootRoute
    }
    '/folders/$folderId': {
      id: '/folders/$folderId'
      path: '/folders/$folderId'
      fullPath: '/folders/$folderId'
      preLoaderRoute: typeof FoldersFolderIdLazyImport
      parentRoute: typeof rootRoute
    }
    '/tasks/$taskId': {
      id: '/tasks/$taskId'
      path: '/tasks/$taskId'
      fullPath: '/tasks/$taskId'
      preLoaderRoute: typeof TasksTaskIdLazyImport
      parentRoute: typeof rootRoute
    }
    '/folders/': {
      id: '/folders/'
      path: '/folders'
      fullPath: '/folders'
      preLoaderRoute: typeof FoldersIndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/login/': {
      id: '/login/'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginIndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/tasks/': {
      id: '/tasks/'
      path: '/tasks'
      fullPath: '/tasks'
      preLoaderRoute: typeof TasksIndexLazyImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/main': typeof MainRoute
  '/home': typeof HomeLazyRoute
  '/folders/$folderId': typeof FoldersFolderIdLazyRoute
  '/tasks/$taskId': typeof TasksTaskIdLazyRoute
  '/folders': typeof FoldersIndexLazyRoute
  '/login': typeof LoginIndexLazyRoute
  '/tasks': typeof TasksIndexLazyRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/main': typeof MainRoute
  '/home': typeof HomeLazyRoute
  '/folders/$folderId': typeof FoldersFolderIdLazyRoute
  '/tasks/$taskId': typeof TasksTaskIdLazyRoute
  '/folders': typeof FoldersIndexLazyRoute
  '/login': typeof LoginIndexLazyRoute
  '/tasks': typeof TasksIndexLazyRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/main': typeof MainRoute
  '/home': typeof HomeLazyRoute
  '/folders/$folderId': typeof FoldersFolderIdLazyRoute
  '/tasks/$taskId': typeof TasksTaskIdLazyRoute
  '/folders/': typeof FoldersIndexLazyRoute
  '/login/': typeof LoginIndexLazyRoute
  '/tasks/': typeof TasksIndexLazyRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/main'
    | '/home'
    | '/folders/$folderId'
    | '/tasks/$taskId'
    | '/folders'
    | '/login'
    | '/tasks'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/main'
    | '/home'
    | '/folders/$folderId'
    | '/tasks/$taskId'
    | '/folders'
    | '/login'
    | '/tasks'
  id:
    | '__root__'
    | '/'
    | '/main'
    | '/home'
    | '/folders/$folderId'
    | '/tasks/$taskId'
    | '/folders/'
    | '/login/'
    | '/tasks/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  MainRoute: typeof MainRoute
  HomeLazyRoute: typeof HomeLazyRoute
  FoldersFolderIdLazyRoute: typeof FoldersFolderIdLazyRoute
  TasksTaskIdLazyRoute: typeof TasksTaskIdLazyRoute
  FoldersIndexLazyRoute: typeof FoldersIndexLazyRoute
  LoginIndexLazyRoute: typeof LoginIndexLazyRoute
  TasksIndexLazyRoute: typeof TasksIndexLazyRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  MainRoute: MainRoute,
  HomeLazyRoute: HomeLazyRoute,
  FoldersFolderIdLazyRoute: FoldersFolderIdLazyRoute,
  TasksTaskIdLazyRoute: TasksTaskIdLazyRoute,
  FoldersIndexLazyRoute: FoldersIndexLazyRoute,
  LoginIndexLazyRoute: LoginIndexLazyRoute,
  TasksIndexLazyRoute: TasksIndexLazyRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/main",
        "/home",
        "/folders/$folderId",
        "/tasks/$taskId",
        "/folders/",
        "/login/",
        "/tasks/"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/main": {
      "filePath": "main.tsx"
    },
    "/home": {
      "filePath": "home.lazy.tsx"
    },
    "/folders/$folderId": {
      "filePath": "folders/$folderId.lazy.tsx"
    },
    "/tasks/$taskId": {
      "filePath": "tasks/$taskId.lazy.tsx"
    },
    "/folders/": {
      "filePath": "folders/index.lazy.tsx"
    },
    "/login/": {
      "filePath": "login/index.lazy.tsx"
    },
    "/tasks/": {
      "filePath": "tasks/index.lazy.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
